### ISSUE TITLE
Will not run on hybrid graphics (primusrun, optirun, bumblebee)

### ISSUE THREAD

**Issue by kylenoteboom** [haikarainen/kit#5] opened 2016-08-04 14:04 UTC
Launching any of the tools except for the importer gets me errors.

I'm running `Arch` on kernel `4.6.4-1`, `x86_64`. DE is `KDE Plasma 5`, version `5.7.3-1`.
Machine is a laptop with a `Intel Core i7-4710HQ` CPU, and an `NVIDIA GeForce GTX 850M` GPU.

A normal run, on my integrated GPU (I don't think it supports the required OpenGL version (yet)):
`./kit-material-designer`
```
GLFW3 initialized.
Initializing material designer..
Constructing script library
Retrieving script library
Initializing script library
Constructed!
Running..
Allocating GL statemanager...
Allocating UI system..
Found 2 monitors!
Error: src/Kit/OpenGL.cpp at 132 in void kit::glfwError(int, const char*): GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
Releasing GL statemanager...
Exception caught: GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig
In file "src/Kit/OpenGL.cpp" on line 132 (in method void kit::glfwError(int, const char*))

GLFW3 terminated.
```
Then a `primusrun` run:
`primusrun ./kit-material-designer`
```
Error: src/Kit/OpenGL.cpp at 132 in void kit::glfwError(int, const char*): GLFW error 65542: EGL: Failed to initialize EGL: EGL is not or could not be initialized
terminate called after throwing an instance of 'kit::Exception'
[1]    9208 abort (core dumped)  primusrun ./kit-material-designer
```

And an `optirun` run for good measure:
`optirun ./kit-material-designer`

```
Error: src/Kit/OpenGL.cpp at 132 in void kit::glfwError(int, const char*): GLFW error 65542: EGL: Failed to initialize EGL: EGL is not or could not be initialized
terminate called after throwing an instance of 'kit::Exception'
```

Other applications work fine with `primusrun`, `optirun` doesn't seem to work at all.

**Comment by haikarainen** [comment] 2016-08-04 14:28
This framework is targeting 4.3 core at a minimum. Run the following command and give me your output:

`glxinfo | grep "core profile version"`

You need `glxinfo`, which is in the `mesa-demos` package on arch.

If you have the required core version, try to do a clean clone of this repo again. I have fixed a bug where it requested the wrong version recently. See https://github.com/haikarainen/kit/commit/75330e4c3c8935cc480d2705b52afe0d24458ea8 (I requested 4.1 compat profile when testing on windows a long time ago and forgot about it)

**Comment by haikarainen** [comment] 2016-08-04 14:31
With regards to `optirun` / `primusrun`, it is known to be very buggy (actually any hybrid graphics in linux systems is very buggy). I recommend you disable your intel chipset  (bios or in OS), and only use your Nvidia chipset. It is what I did when I had a 840M.

Anyway, we both have the same intel driver, so Im pretty sure you just need to do a new clone/just a pull

**Comment by vincegogh** [comment] 2016-08-05 04:31
> This framework is targeting 4.3 core at a minimum.

So does that mean that [this should be set to 4.3 too?](https://github.com/haikarainen/kit/blob/master/src/Kit/OpenGL.cpp#L69) Also, you might want to add that to the readme. 4.3 is still quite high, so it might be a good idea to warn people before they try to run anything.

**Comment by haikarainen** [comment] 2016-08-05 07:10
Ah yes @vincegogh that definitely needs to be changed. Good eye! Yes 4.3 is still pretty high, but in my experience most drivers (AMD, Nvidia, Intel) supports both in Windows & Linux. 

Any hardware that's too old to support it is probably too old to support the Kit renderer as it is anyway. Please do tell me if you find a configuration that should be supported but isn't.

**Comment by haikarainen** [comment] 2016-08-06 08:42
I just realized that GLFW is trying to initialize EGL. I have no idea why it would do this since I dont support OpenGL ES. Maybe theres a logical explanation to this, but it looks like a source of the error.

**Comment by kylenoteboom** [comment] 2016-08-06 10:19
I deleted the repo and recloned it, I still get the same errors.

```
glxinfo | grep "core profile version"
Max core profile version: 3.3
OpenGL core profile version string: 3.3 (Core Profile) Mesa 12.0.1
```
```
primusrun glxinfo | grep "core profile version"
OpenGL core profile version string: 4.5.0 NVIDIA 367.35
```

```
optirun glxinfo | grep "core profile version"

```

Sorry for the late reply, been trying to run on NVIDIA only but haven't been able to get there yet.

**Comment by smdrz** [comment] 2016-08-06 10:28
```
GLFW3 initialized.
Initializing material designer..
Constructing script library
Retrieving script library
Initializing script library
Constructed!
Running..
Allocating GL statemanager...
Allocating UI system..
Found 1 monitors!
Initializing OpenGL
OpenGL initialized -- version 4.3.0 NVIDIA 367.35, GLSL 4.30 NVIDIA via Cg compiler.
Error: src/Kit/Font.cpp at 185 in static kit::Font::Ptr kit::Font::load(std::string): Failed to load font from file
```

**Comment by haikarainen** [comment] 2016-08-06 10:29
@kylenoteboom  Thank you for following up, highly appreciated! 

Allright, the first issue (won't run with your intel setup), is caused by your driver only supporting version 3.3, which is *really* weird! I also have Intel hardware (although I have HD 530 and not HD 4600, but your gpu should still support 4.3!), using the exact same mesa version and I get this line:

```
[fredrik@fredrik-laptop kit]$ glxinfo | grep "core profile version"
    Max core profile version: 4.3
OpenGL core profile version string: 4.3 (Core Profile) Mesa 12.0.1
```

Second issue (primusrun) is not about the opengl version, but the fact that EGL fails to initialize. I have created an issue with GLFW on this.

**Comment by haikarainen** [comment] 2016-08-06 10:30
@smdrz You need to run it from the dist folder, that output is not relevant to this issue (Your GPU setup is just fine! :)

**Comment by smdrz** [comment] 2016-08-06 10:31
@haikarainen primus only works with glx calls nothing else

**Comment by haikarainen** [comment] 2016-08-06 10:34
@smdrz Thank you, that explains a lot! I wonder why GLFW wouldnt fall back to GLX if EGL fails though.  I wonder if you can somehow force GLX or disable EGL (possibly by building GLFW yourself?)

**Comment by haikarainen** [comment] 2016-08-06 10:39
I think I've found a solution, applying fix, pushing soon.

**Comment by haikarainen** [comment] 2016-08-06 10:44
I have applied a possible fix (check commit https://github.com/haikarainen/kit/commit/687ce389150d9747599f1d21b196ad23c9096934). Please verify @kylenoteboom

**Comment by kylenoteboom** [comment] 2016-08-06 11:39
```
primusrun ./kit-world-editor 
Error: src/Kit/OpenGL.cpp at 132 in void kit::glfwError(int, const char*): GLFW error 65542: EGL: Failed to initialize EGL: EGL is not or could not be initialized
terminate called after throwing an instance of 'kit::Exception'
[1]    9239 abort (core dumped)  primusrun ./kit-world-editor
```

**Comment by haikarainen** [comment] 2016-08-06 11:44
@kylenoteboom Have you fetched the new commits, ran "make clean" followed by "make" and "make install", and then the same on the tool?

**Comment by kylenoteboom** [comment] 2016-08-06 11:44
I am sure I did, I'll do it again just to be sure.

**Comment by haikarainen** [comment] 2016-08-06 11:47
Thanks! That's weird though.  Will have to wait for response on the GLFW issue.

**Comment by kylenoteboom** [comment] 2016-08-06 11:51
Running make install on world-editor:
```
sudo make install
mkdir: cannot create directory ‘bin’: File exists
g++ -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-parameter -DKIT_DEBUG -g -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libdrm  -L/usr/lib64 -lkit -lglfw -lfreetype -lGL build/src/Application.o build/src/BakeTool.o build/src/EditorCamera.o build/src/EditorComponent.o build/src/main.o build/src/PaintTool.o build/src/PropTool.o build/src/SculptTool.o build/src/WorldEditorState.o -o bin/kit-world-editor
cp bin/kit-world-editor ../../dist/
cp: cannot create regular file '../../dist/': Not a directory
make: *** [makefile:25: install] Error 1
```

And material-editor:
```
sudo make install
mkdir: cannot create directory ‘bin’: File exists
g++ -std=c++14 -Wall -Wextra -Wpedantic -Wno-unused-parameter -DKIT_DEBUG -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libdrm  -L/usr/lib64 -lkit -lglfw -lfreetype -lGL build/src/Application.o build/src/main.o build/src/MaterialDesignerState.o -o bin/kit-material-designer
cp bin/kit-material-designer ../../dist/
cp: cannot create regular file '../../dist/': Not a directory
make: *** [makefile:26: install] Error 1
```

**Comment by haikarainen** [comment] 2016-08-06 11:55
Please create a different issue for that.

**Comment by kylenoteboom** [comment] 2016-08-06 11:57
@haikarainen 
That was because I deleted the `dist` folder, it's pretty big. No issue needed for that, it worked as soon as I added got that folder in the repo again.

**Comment by haikarainen** [comment] 2016-08-06 12:01
@kylenoteboom FWIW the data folder in dist is _needed_ for any kit application to run. You can trim it down by removing unneeded assets. You really only need 1 folder under data/env for example,  and the only engine-critical texture is brdf.tga. Note however that some resources are hardcoded into the tools etc.

**Comment by Guldoman** [comment] 2016-08-06 13:53
Works on Arch on kernel 4.6.4-1 with an NVIDIA GeForce GTX 970m with latest glfw from git.

**Comment by kylenoteboom** [comment] 2016-08-06 14:10
@Guldoman Are you using Bumblebee?

**Comment by Guldoman** [comment] 2016-08-06 14:15
Yes

**Comment by Guldoman** [comment] 2016-08-06 15:27
Copy [PKGBUILD.txt](https://github.com/haikarainen/kit/files/405058/PKGBUILD.txt) in a folder and rename it to `PKGBUILD`. Run `makepkg`. This generates a pkg.tar.xz file.
Then run `sudo pacman -U <the file name>.pkg.tar.xz`.
Now if you recompile kit and its tools it should work.

**Comment by kylenoteboom** [comment] 2016-08-06 15:44
@Guldoman I've been trying to do that. The `AUR package` doesn't compile for me. [Here's a gist of the AUR PKGBUILD errors](https://gist.github.com/kylenoteboom/36f600bc6ff6419f0ce61f1a1e12e89f).

As for your `PKGBUILD`, I managed to install it but then `make` spits out the following:
```
make      
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
```

I also tried compiling from the `GLFW git` myself, but I get the same result as your `PKGBUILD`.

**Comment by haikarainen** [comment] 2016-08-06 15:54
I'm closing this since it's pretty obvious that Kit is not the problem. You may keep discussing though.

**Closed by haikarainen** 2016-08-06 15:54 UTC
Labels: bug

**Comment by Guldoman** [comment] 2016-08-06 16:03
Try doing this:
* `git clone https://github.com/glfw/glfw.git`
* `cd glfw`
* `mkdir build`
* `cd build`
* `cmake ..`
* `make`

What is the output of make?

**Comment by kylenoteboom** [comment] 2016-08-06 16:20
@Guldoman I did that and it compiled properly, so thanks for that. However, when I `make install` that, `kit`'s `make` still complains it cannot find `glfw`:
```
make
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
Package glfw3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glfw3.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glfw3' found
```

I checked and `glfw3.pc` is inside `/usr/local/lib/pkgconfig`:
```
ls /usr/local/lib/pkgconfig 
glfw3.pc
```
Where it should be according to `GLFW git`'s `make install` result:
```
sudo make install
[ 15%] Built target glfw
[ 18%] Built target heightmap
[ 21%] Built target gears
[ 26%] Built target particles
[ 29%] Built target wave
[ 31%] Built target boing
[ 33%] Built target simple
[ 36%] Built target splitview
[ 39%] Built target reopen
[ 42%] Built target joysticks
[ 46%] Built target monitors
[ 49%] Built target iconify
[ 53%] Built target glfwinfo
[ 57%] Built target gamma
[ 60%] Built target icon
[ 64%] Built target tearing
[ 68%] Built target empty
[ 71%] Built target cursor
[ 75%] Built target threads
[ 79%] Built target clipboard
[ 82%] Built target title
[ 85%] Built target sharing
[ 89%] Built target windows
[ 93%] Built target events
[ 97%] Built target msaa
[100%] Built target timeout
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/include/GLFW
-- Installing: /usr/local/include/GLFW/glfw3native.h
-- Installing: /usr/local/include/GLFW/glfw3.h
-- Installing: /usr/local/lib/cmake/glfw3/glfw3Config.cmake
-- Installing: /usr/local/lib/cmake/glfw3/glfw3ConfigVersion.cmake
-- Installing: /usr/local/lib/cmake/glfw3/glfw3Targets.cmake
-- Installing: /usr/local/lib/cmake/glfw3/glfw3Targets-noconfig.cmake
-- Installing: /usr/local/lib/pkgconfig/glfw3.pc
-- Installing: /usr/local/lib/libglfw3.a
```

What's weird is that `Arch`'s `glfw-x11 package` is found properly, it just doesn't run for me.

**Comment by haikarainen** [comment] 2016-08-06 16:30
Shouldn't it be in /usr, not /usr/local? I'm not sure about pkgconfig, but most stuff only looks in /usr by default

**Comment by Guldoman** [comment] 2016-08-06 16:41
Uuups my bad. I can't PKGBUILD...
This is the correct one: 
[PKGBUILD.txt](https://github.com/haikarainen/kit/files/405082/PKGBUILD.txt)

**Comment by kylenoteboom** [comment] 2016-08-06 16:49
@Guldoman Thanks that worked! Now there's just a runtime error regarding a font file, but that'll have to wait for its own issue.

**Comment by haikarainen** [comment] 2016-08-06 16:50
@kylenoteboom You have to run the tools in the dist folder. Type "make install" in a tool directory to copy the binaries there

**Comment by kylenoteboom** [comment] 2016-08-06 17:53
@haikarainen Yes, that did it.
